### PR TITLE
Fix wrong error message.

### PR DESCRIPTION
**Pull request by ahi**
if the parameter from get_class is null, it returns the name of outer class.

### CODE REVIEW

**Comment by wick-ed** [comment]
@appserver-ci Test this please

**Comment by wick-ed** [comment]
@appserver-ci test this please

**Comment by wick-ed** [comment]
Hi @ahi ,
can you please also update the `CHANGELOG.md` and the `builds.default.properties` files with the new patch version and a short description of your changes?

Thanks

**Comment by wick-ed** [comment]
Great! Thanks a lot @ahi  :)

**Comment by ahi** [comment]
gladly!

**Pull request merged**
